In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

import gc
import os

Custom defined functions.

In [2]:
from utils import agg_columns, remove_nan_columns

In [3]:
dataset_dir = "dataset"

Since the dataset is large, we restrict to use the first `NUM_ROWS` of each table. Set to `None` to include all data.

In [4]:
NUM_ROWS = 250000

## Feature engineering

### The bureau tables

Load the bureau tables.

In [5]:
bureau_balance_df = pd.read_csv(os.path.join(dataset_dir, "bureau_balance.csv")).iloc[:NUM_ROWS]
bureau_df = pd.read_csv(os.path.join(dataset_dir, "bureau.csv")).iloc[:NUM_ROWS]

Aggregate the *bureau_balance* table and merge it with the *bureau* table.

In [6]:
agg_bureau_balance_df = agg_columns(bureau_balance_df, groupby_columns=["SK_ID_BUREAU"], prefix="BAL").iloc[:NUM_ROWS]
merged_bureau_bureau_balance_df = pd.merge(bureau_df, agg_bureau_balance_df, on="SK_ID_BUREAU", how="left").iloc[:NUM_ROWS]

Free memory.

In [7]:
del bureau_balance_df, bureau_df, agg_bureau_balance_df
gc.collect()

0

Aggregate the merged table and merge it with the main *applications* table.

In [8]:
merged_bureau_df = agg_columns(
    merged_bureau_bureau_balance_df,
    groupby_columns=["SK_ID_CURR"],
    exclude_columns=["SK_ID_BUREAU"],
    prefix="BUREAU"
)

Free memory.

In [9]:
del merged_bureau_bureau_balance_df
gc.collect()

0

In [10]:
merged_bureau_df

,SK_ID_CURR,BUREAU_DAYS_CREDIT_count,BUREAU_DAYS_CREDIT_mean,BUREAU_DAYS_CREDIT_sum,BUREAU_DAYS_CREDIT_min,BUREAU_DAYS_CREDIT_max,BUREAU_CREDIT_DAY_OVERDUE_count,BUREAU_CREDIT_DAY_OVERDUE_mean,BUREAU_CREDIT_DAY_OVERDUE_sum,BUREAU_CREDIT_DAY_OVERDUE_min,...,BUREAU_CREDIT_TYPE_Microloan_count,BUREAU_CREDIT_TYPE_Microloan_count_norm,BUREAU_CREDIT_TYPE_Mobile operator loan_count,BUREAU_CREDIT_TYPE_Mobile operator loan_count_norm,BUREAU_CREDIT_TYPE_Mortgage_count,BUREAU_CREDIT_TYPE_Mortgage_count_norm,BUREAU_CREDIT_TYPE_Real estate loan_count,BUREAU_CREDIT_TYPE_Real estate loan_count_norm,BUREAU_CREDIT_TYPE_Unknown type of loan_count,BUREAU_CREDIT_TYPE_Unknown type of loan_count_norm
0,100001,7,-735.000000,-5145,-1572,-49,7,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
1,100016,6,-677.833333,-4067,-1634,-128,6,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
2,100017,6,-1944.333333,-11666,-2881,-909,6,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
3,100019,2,-495.000000,-990,-495,-495,2,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
4,100030,5,-949.000000,-4745,-1547,-418,5,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57840,456207,3,-1269.000000,-3807,-1835,-379,3,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
57841,456217,3,-1090.333333,-3271,-1537,-804,3,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
57842,456241,1,-2180.000000,-2180,-2180,-2180,1,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
57843,456243,5,-842.800000,-4214,-2358,-154,5,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
57844,456247,7,-874.285714,-6120,-2028,-287,7,0.0,0,0,...,0,0.0,0,0.0,1,0.142857,0,0.0,0,0.0

### The Home Credit tables

Load the Home Credit tables.

In [11]:
credit_card_balance_df = pd.read_csv(os.path.join(dataset_dir, "credit_card_balance.csv")).iloc[:NUM_ROWS]
installments_payments_df = pd.read_csv(os.path.join(dataset_dir, "installments_payments.csv")).iloc[:NUM_ROWS]
POS_CASH_balance_df = pd.read_csv(os.path.join(dataset_dir, "POS_CASH_balance.csv")).iloc[:NUM_ROWS]
previous_application_df = pd.read_csv(os.path.join(dataset_dir, "previous_application.csv")).iloc[:NUM_ROWS]

Aggregate the *POS_CASH_balance* table and merge it with the *previous_application* table

In [12]:
agg_POS_CASH_balance_df = agg_columns(
    POS_CASH_balance_df,
    groupby_columns=["SK_ID_PREV"],
    exclude_columns=["SK_ID_CURR"],
    prefix="POS"
)
merged_previous_application_df = pd.merge(previous_application_df, agg_POS_CASH_balance_df, on="SK_ID_PREV", how="left")

Free memory.

In [13]:
del POS_CASH_balance_df, previous_application_df, agg_POS_CASH_balance_df
gc.collect()

0

Aggregate the *installments_payment* table and merge it with the *previous_application* table

In [14]:
agg_installments_payments_df = agg_columns(
    installments_payments_df,
    groupby_columns=["SK_ID_PREV"],
    exclude_columns=["SK_ID_CURR"],
    prefix="INSTALL"
)
merged_previous_application_df = pd.merge(merged_previous_application_df, agg_installments_payments_df, on="SK_ID_PREV", how="left")

Free memory.

In [15]:
del installments_payments_df, agg_installments_payments_df
gc.collect()

0

Aggregate the *credit_card_balance* table and merge it with the *previous_application* table

In [16]:
agg_credit_card_balance_df = agg_columns(
    credit_card_balance_df,
    groupby_columns=["SK_ID_PREV"],
    exclude_columns=["SK_ID_CURR"],
    prefix="CC"
)
merged_previous_application_df = pd.merge(merged_previous_application_df, agg_credit_card_balance_df, on="SK_ID_PREV", how="left")

Free memory.

In [17]:
del credit_card_balance_df, agg_credit_card_balance_df
gc.collect()

0

Aggregate the merged *previous_application* table.

In [18]:
merged_home_credit_df = agg_columns(
    merged_previous_application_df,
    groupby_columns=["SK_ID_CURR"],
    exclude_columns=["SK_ID_PREV"],
    prefix="PREV"
)

Free memory.

In [19]:
del merged_previous_application_df
gc.collect()

0

Merge the aggregated bureau the Home Credit dataframes.

In [20]:
to_merge_df = pd.merge(merged_bureau_df, merged_home_credit_df, on="SK_ID_CURR", how="outer")

Free memory.

In [21]:
del merged_bureau_df, merged_home_credit_df
gc.collect()

0

In [22]:
to_merge_df.to_pickle("dataset/to_merge_df.pkl")

## Data preprocessing

Load the main *application_train.csv* table and merge it with the aggregated data table.

In [23]:
applications_df = pd.read_csv(os.path.join(dataset_dir, "application_train.csv")).iloc[:NUM_ROWS]

The `DAYS_EMPLOYED` column uses the value `365243` (which is aroung 1000 years) to mark applicants that are not employed. Replace it with `NaN` so it does not distort the feature scale

In [24]:
applications_df["DAYS_EMPLOYED"] = applications_df["DAYS_EMPLOYED"].replace(365243, np.nan)

In [25]:
from sklearn.model_selection import train_test_split

applications_train, applications_test = train_test_split(
    applications_df,
    train_size=0.7,
    random_state=42,
    stratify=applications_df["TARGET"]
)

applications_train = applications_train.reset_index(drop=True)
applications_test = applications_test.reset_index(drop=True)

Free memory.

In [26]:
del applications_df
gc.collect()

16

Process the training set.

In [27]:
applications_train = pd.merge(applications_train, to_merge_df, on="SK_ID_CURR", how="left")
applications_train = pd.get_dummies(applications_train, drop_first=True)
applications_train = remove_nan_columns(applications_train)

We remove the ID column since it does not have any valuable information

In [28]:
applications_train = applications_train.drop(columns=["SK_ID_CURR"])

In [29]:
applications_train

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_Yes
0,1,0,94500.0,396000.0,19390.5,396000.0,0.018850,-20418,NaN,-2140.0,...,False,False,False,False,False,False,False,False,False,False
1,0,2,360000.0,975771.0,28660.5,814500.0,0.046220,-16532,-2286.0,-6054.0,...,False,False,True,False,False,False,False,True,False,False
2,0,0,135000.0,808650.0,26217.0,675000.0,0.007330,-18914,-5265.0,-10905.0,...,False,False,True,False,False,False,False,True,False,False
3,1,0,112500.0,220500.0,14913.0,220500.0,0.022625,-19499,-4481.0,-11105.0,...,False,False,False,False,False,False,True,False,False,False
4,1,0,147600.0,225000.0,17905.5,225000.0,0.001417,-11688,-1989.0,-5754.0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174995,0,1,193500.0,1260000.0,36841.5,1260000.0,0.010500,-10918,-989.0,-2219.0,...,False,False,False,False,False,False,False,False,False,False
174996,0,0,675000.0,1633473.0,45049.5,1363500.0,0.016612,-21788,-2856.0,-5370.0,...,False,False,False,False,False,False,False,True,False,False
174997,0,0,90000.0,630747.0,20344.5,526500.0,0.006852,-23461,NaN,-5345.0,...,False,False,False,False,False,False,False,False,False,False
174998,0,0,157500.0,461358.0,39595.5,427500.0,0.007330,-10485,-1057.0,-4593.0,...,True,False,False,False,False,False,False,True,False,False
174999,0,2,90000.0,1078200.0,31522.5,900000.0,0.009630,-11695,-2923.0,-2078.0,...,False,False,False,False,False,False,False,False,False,False

Process the test set.

In [30]:
applications_test = pd.merge(applications_test, to_merge_df, on="SK_ID_CURR", how="left")
applications_test = pd.get_dummies(applications_test, drop_first=True)

Align test features to match the features from the training set.

In [31]:
applications_test = applications_test.reindex(columns=applications_train.columns, fill_value=0)

In [32]:
applications_test

,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,...,FONDKAPREMONT_MODE_reg oper spec account,HOUSETYPE_MODE_specific housing,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_Yes
0,0,0,112500.0,450000.0,21780.0,450000.0,0.015221,-13506,-1354.0,-2268.0,...,False,False,False,False,False,False,False,False,False,False
1,0,2,67500.0,170640.0,6561.0,135000.0,0.020246,-11356,-4524.0,-4192.0,...,False,False,False,False,False,False,False,True,False,False
2,0,0,135000.0,542133.0,29011.5,468000.0,0.018634,-22619,NaN,-12314.0,...,False,False,False,False,False,False,False,False,False,False
3,0,0,135000.0,316125.0,21253.5,261000.0,0.019689,-14059,-859.0,-1034.0,...,False,False,False,False,False,False,False,False,True,True
4,0,0,157500.0,203760.0,21523.5,180000.0,0.046220,-19833,-2033.0,-9074.0,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74995,0,0,225000.0,1125000.0,40410.0,1125000.0,0.019689,-15777,-9160.0,-598.0,...,False,False,False,False,False,False,False,False,False,False
74996,0,0,211500.0,297000.0,23593.5,297000.0,0.003813,-22913,NaN,-9241.0,...,True,False,False,True,False,False,False,False,False,False
74997,0,0,180000.0,1288350.0,37800.0,1125000.0,0.018850,-13263,-4934.0,-369.0,...,False,False,False,False,False,False,False,False,False,False
74998,0,1,135000.0,543037.5,31302.0,463500.0,0.020246,-13689,-1172.0,-2154.0,...,False,False,False,False,False,False,False,False,False,False
74999,0,0,252000.0,765000.0,38250.0,765000.0,0.007020,-17367,-7384.0,-5657.0,...,False,False,False,False,False,False,False,False,False,False

In [33]:
from sklearn.impute import SimpleImputer

In [34]:
imp_mean = SimpleImputer(strategy="mean").set_output(transform="pandas")
imp_mean.fit(applications_train)
applications_train = imp_mean.transform(applications_train)
applications_test = imp_mean.transform(applications_test)

Save the preprocessed data to disk.

In [35]:
applications_train.to_csv(os.path.join(dataset_dir, "train_set.csv"), index=False)
applications_test.to_csv(os.path.join(dataset_dir, "test_set.csv"), index=False)