In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

import gc
import os

Custom defined functions.

In [2]:
from utils import agg_columns, remove_nan_columns

In [3]:
dataset_dir = "dataset"

Since the dataset is large, we restrict to use the first `NUM_ROWS` of each table. Set to `None` to include all data.

In [4]:
NUM_ROWS = 50000

## Feature engineering

### The bureau tables

Load the bureau tables.

In [5]:
bureau_balance_df = pd.read_csv(os.path.join(dataset_dir, "bureau_balance.csv")).iloc[:NUM_ROWS]
bureau_df = pd.read_csv(os.path.join(dataset_dir, "bureau.csv")).iloc[:NUM_ROWS]

Aggregate the *bureau_balance* table and merge it with the *bureau* table.

In [6]:
agg_bureau_balance_df = agg_columns(bureau_balance_df, groupby_columns=["SK_ID_BUREAU"], prefix="BAL").iloc[:NUM_ROWS]
merged_bureau_bureau_balance_df = pd.merge(bureau_df, agg_bureau_balance_df, on="SK_ID_BUREAU", how="left").iloc[:NUM_ROWS]

Free memory.

In [7]:
del bureau_balance_df, bureau_df, agg_bureau_balance_df
gc.collect()

10

Aggregate the merged table and merge it with the main *applications* table.

In [8]:
merged_bureau_df = agg_columns(
    merged_bureau_bureau_balance_df,
    groupby_columns=["SK_ID_CURR"],
    exclude_columns=["SK_ID_BUREAU"],
    prefix="BUREAU"
)

Free memory.

In [9]:
del merged_bureau_bureau_balance_df
gc.collect()

0

In [10]:
merged_bureau_df

,SK_ID_CURR,BUREAU_DAYS_CREDIT_count,BUREAU_DAYS_CREDIT_mean,BUREAU_DAYS_CREDIT_sum,BUREAU_DAYS_CREDIT_min,BUREAU_DAYS_CREDIT_max,BUREAU_CREDIT_DAY_OVERDUE_count,BUREAU_CREDIT_DAY_OVERDUE_mean,BUREAU_CREDIT_DAY_OVERDUE_sum,BUREAU_CREDIT_DAY_OVERDUE_min,...,BUREAU_CREDIT_TYPE_Loan for working capital replenishment_count,BUREAU_CREDIT_TYPE_Loan for working capital replenishment_count_norm,BUREAU_CREDIT_TYPE_Microloan_count,BUREAU_CREDIT_TYPE_Microloan_count_norm,BUREAU_CREDIT_TYPE_Mortgage_count,BUREAU_CREDIT_TYPE_Mortgage_count_norm,BUREAU_CREDIT_TYPE_Real estate loan_count,BUREAU_CREDIT_TYPE_Real estate loan_count_norm,BUREAU_CREDIT_TYPE_Unknown type of loan_count,BUREAU_CREDIT_TYPE_Unknown type of loan_count_norm
0,100016,6,-677.833333,-4067,-1634,-128,6,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
1,100053,7,-2287.714286,-16014,-2893,-1764,7,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
2,100165,2,-1775.000000,-3550,-2325,-1225,2,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
3,100166,13,-906.538462,-11785,-2058,-106,13,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
4,100294,5,-774.400000,-3872,-1137,-217,5,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10166,456116,2,-1376.500000,-2753,-1812,-941,2,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
10167,456179,4,-854.250000,-3417,-993,-684,4,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
10168,456181,3,-420.666667,-1262,-599,-101,3,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
10169,456243,5,-842.800000,-4214,-2358,-154,5,0.0,0,0,...,0,0.0,0,0.0,0,0.000000,0,0.0,0,0.0
10170,456247,7,-874.285714,-6120,-2028,-287,7,0.0,0,0,...,0,0.0,0,0.0,1,0.142857,0,0.0,0,0.0

### The Home Credit tables

Load the Home Credit tables.

In [11]:
credit_card_balance_df = pd.read_csv(os.path.join(dataset_dir, "credit_card_balance.csv")).iloc[:NUM_ROWS]
installments_payments_df = pd.read_csv(os.path.join(dataset_dir, "installments_payments.csv")).iloc[:NUM_ROWS]
POS_CASH_balance_df = pd.read_csv(os.path.join(dataset_dir, "POS_CASH_balance.csv")).iloc[:NUM_ROWS]
previous_application_df = pd.read_csv(os.path.join(dataset_dir, "previous_application.csv")).iloc[:NUM_ROWS]

Aggregate the *POS_CASH_balance* table and merge it with the *previous_application* table

In [12]:
agg_POS_CASH_balance_df = agg_columns(
    POS_CASH_balance_df,
    groupby_columns=["SK_ID_PREV"],
    exclude_columns=["SK_ID_CURR"],
    prefix="POS"
)
merged_previous_application_df = pd.merge(previous_application_df, agg_POS_CASH_balance_df, on="SK_ID_PREV", how="left")

Free memory.

In [13]:
del POS_CASH_balance_df, previous_application_df, agg_POS_CASH_balance_df
gc.collect()

0

Aggregate the *installments_payment* table and merge it with the *previous_application* table

In [14]:
agg_installments_payments_df = agg_columns(
    installments_payments_df,
    groupby_columns=["SK_ID_PREV"],
    exclude_columns=["SK_ID_CURR"],
    prefix="INSTALL"
)
merged_previous_application_df = pd.merge(merged_previous_application_df, agg_installments_payments_df, on="SK_ID_PREV", how="left")

Free memory.

In [15]:
del installments_payments_df, agg_installments_payments_df
gc.collect()

0

Aggregate the *credit_card_balance* table and merge it with the *previous_application* table

In [16]:
agg_credit_card_balance_df = agg_columns(
    credit_card_balance_df,
    groupby_columns=["SK_ID_PREV"],
    exclude_columns=["SK_ID_CURR"],
    prefix="CC"
)
merged_previous_application_df = pd.merge(merged_previous_application_df, agg_credit_card_balance_df, on="SK_ID_PREV", how="left")

Free memory.

In [17]:
del credit_card_balance_df, agg_credit_card_balance_df
gc.collect()

0

Aggregate the merged *previous_application* table.

In [18]:
merged_home_credit_df = agg_columns(
    merged_previous_application_df,
    groupby_columns=["SK_ID_CURR"],
    exclude_columns=["SK_ID_PREV"],
    prefix="PREV"
)

Free memory.

In [19]:
del merged_previous_application_df
gc.collect()

0

Merge the aggregated bureau the Home Credit dataframes.

In [20]:
to_merge_df = pd.merge(merged_bureau_df, merged_home_credit_df, on="SK_ID_CURR", how="outer")

Free memory.

In [21]:
del merged_bureau_df, merged_home_credit_df
gc.collect()

0

In [40]:
to_merge_df.to_pickle("dataset/to_merge_df.pkl")

## Data preprocessing

Load the main *application_train.csv* table and merge it with the aggregated data table.

In [22]:
applications_df = pd.read_csv(os.path.join(dataset_dir, "application_train.csv")).iloc[:NUM_ROWS]

In [23]:
from sklearn.model_selection import train_test_split

applications_train, applications_test = train_test_split(
    applications_df,
    train_size=0.7,
    random_state=42,
    stratify=applications_df["TARGET"]
)

applications_train = applications_train.reset_index(drop=True)
applications_test = applications_test.reset_index(drop=True)

Free memory.

In [24]:
del applications_df
gc.collect()

20

Process the training set.

In [25]:
applications_train = pd.merge(applications_train, to_merge_df, on="SK_ID_CURR", how="left")
applications_train = pd.get_dummies(applications_train)
applications_train = remove_nan_columns(applications_train)

In [26]:
applications_train

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,112548,0,0,90000.0,1350000.0,37125.0,1350000.0,0.015221,-22963,365243,...,False,False,False,False,False,False,False,False,False,False
1,130354,0,2,180000.0,662026.5,36045.0,571500.0,0.035792,-12638,-1173,...,False,False,False,False,False,False,False,False,False,False
2,116517,0,0,90000.0,239850.0,22540.5,225000.0,0.007114,-19506,365243,...,False,False,False,False,False,False,False,False,False,False
3,156260,0,0,135000.0,942300.0,27135.0,675000.0,0.003541,-21059,365243,...,False,False,False,False,False,False,False,False,False,False
4,149143,0,2,157500.0,288873.0,22950.0,238500.0,0.020246,-12951,-5111,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34995,103720,0,0,74250.0,263686.5,13522.5,238500.0,0.007330,-24499,365243,...,False,False,False,False,False,True,False,False,True,False
34996,137390,0,0,371925.0,1762110.0,46611.0,1575000.0,0.046220,-19649,-1145,...,False,False,False,False,False,False,True,False,True,False
34997,134820,0,2,315000.0,675000.0,65889.0,675000.0,0.032561,-11689,-340,...,False,False,False,False,False,False,False,False,False,False
34998,123115,0,0,49500.0,152820.0,8770.5,135000.0,0.024610,-24479,365243,...,False,False,False,False,False,False,True,False,True,False
34999,141635,0,0,135000.0,1125000.0,30937.5,1125000.0,0.010147,-8505,-419,...,False,False,False,False,False,False,False,False,True,False

Process the test set.

In [27]:
applications_test = pd.merge(applications_test, to_merge_df, on="SK_ID_CURR", how="left")
applications_test = pd.get_dummies(applications_test)

Align test features to match the features from the training set.

In [28]:
applications_test = applications_test.reindex(columns=applications_train.columns, fill_value=0)

In [29]:
applications_test

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,145947,0,0,225000.0,1002870.0,42619.5,922500.0,0.006305,-20091,-8908,...,False,False,False,False,False,True,False,False,True,False
1,129408,0,2,180000.0,152820.0,17370.0,135000.0,0.014464,-10454,-505,...,False,False,False,False,False,False,False,False,False,False
2,143657,0,0,247500.0,640080.0,24259.5,450000.0,0.018850,-19569,365243,...,False,False,False,False,False,False,False,False,False,False
3,156624,0,0,76500.0,675000.0,19867.5,675000.0,0.010276,-21042,-3675,...,False,False,False,False,False,False,False,False,False,False
4,111946,0,0,112500.0,225000.0,12694.5,225000.0,0.028663,-23962,365243,...,False,False,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,143648,0,3,315000.0,1312110.0,52168.5,1125000.0,0.020713,-21390,-2370,...,False,False,False,False,False,False,False,False,False,False
14996,102201,0,1,168750.0,192528.0,9495.0,126000.0,0.016612,-11991,-2974,...,False,False,False,False,False,False,False,False,False,False
14997,150413,0,2,157500.0,495000.0,30411.0,495000.0,0.015221,-10856,-1116,...,False,False,False,False,False,False,False,False,False,False
14998,103130,0,0,112500.0,571446.0,16839.0,477000.0,0.022625,-23123,-2965,...,False,False,False,False,False,True,False,False,True,False
14999,133978,1,0,180000.0,771493.5,31419.0,666000.0,0.018029,-10550,-1107,...,False,False,False,False,False,False,True,False,True,False

In [30]:
from sklearn.impute import SimpleImputer

In [31]:
imp_mean = SimpleImputer(strategy="mean").set_output(transform="pandas")
imp_mean.fit(applications_train)
applications_train = imp_mean.transform(applications_train)
applications_test = imp_mean.transform(applications_test)

Save the preprocessed data to disk.

In [32]:
applications_train.to_csv(os.path.join(dataset_dir, "train_set.csv"), index=False)
applications_test.to_csv(os.path.join(dataset_dir, "test_set.csv"), index=False)